In [6]:
import numpy as np 


defines sine and cosine functions\

In [2]:
def sin(x):
    return np.sin(x)

def cos_x(x):
    return np.cos(x)

tabulates sine and cosine array values 

In [3]:
x_values = np.linspace(0, 2, 1000)
sin_results = np.sin(x_values)
cos_results = np.cos(x_values)
tab_results = np.vstack((x_values, sin_results, cos_results)).T

In [4]:
print(tab_results)

[[ 0.          0.          1.        ]
 [ 0.002002    0.002002    0.999998  ]
 [ 0.004004    0.00400399  0.99999198]
 ...
 [ 1.995996    0.91095639 -0.41250268]
 [ 1.997998    0.91012873 -0.41432559]
 [ 2.          0.90929743 -0.41614684]]


In [5]:

print(f"{'x':<10}{'sin(x)':<15}{'cos(x)':<15}")
for i in range(10):
    print(f"{x_values[i]:<10}{sin_results[i]:<15}{cos_results[i]:<15}")


x         sin(x)         cos(x)         
0.0       0.0            1.0            
0.0020020020020020020.00200200066466092340.9999979959946613
0.0040040040040040040.0040039933052818070.9999919839866774
0.0060060060060060060.00600596989785477050.9999819640001444
0.0080080080080080080.0080079224184362550.9999679360752225
0.010010010010010010.0100098428431791840.9999499002681359
0.0120120120120120120.0120117231483651190.9999278566511721
0.0140140140140140140.0140135553104364220.9999018053126824
0.0160160160160160160.0160153313060284150.9998717463570806
0.0180180180180180180.018017043112001530.9998376799048435
